; ==========
; Configuration File - Docker
; ==========

; Battle Server Settings 
[Battle-Server]
Enabled = true
BindIP = 0.0.0.0
WebPort = 9800
Port = 1119

; Message of the Day
MotdEnabled = true
MotdEnabledWhenWorldLoads = false
Motd = Welcome to Blizzless D3!
MotdEnabledRemote = false
MotdRemoteUrl = https://your-site.local/yourmotd

; REST Service Settings
[REST]
IP = 0.0.0.0
PublicIP = us.actual.battle.net
PORT = 83
Public = true

; Game Server Settings
[Game-Server]
Enabled = true
CoreActive = true
BindIP = 0.0.0.0
WebPort = 9001
Port = 1345
BindIPv6 = ::
DRLGemu = true

; NAT Settings
[NAT]
Enabled = True
PublicIP = 127.0.0.1

; ==========
; Game Modding Configuration
RateExp = 1
RateMoney = 1
RateDrop = 1
RateChangeDrop = 1
RateMonsterHP = 1
RateMonsterDMG = 1

ChanceHighQualityUnidentified = 30
ChanceNormalUnidentified = 5

BossHealthMultiplier = 6
BossDamageMultiplier = 3

NephalemRiftProgressMultiplier = 1

HealthPotionRestorePercentage = 60
HealthPotionCooldown = 30
ResurrectionCharges = 3

UnlockAllWaypoints = false

StrengthMultiplier = 1
StrengthParagonMultiplier = 1
DexterityMultiplier = 1
DexterityParagonMultiplier = 1
IntelligenceMultiplier = 1
IntelligenceParagonMultiplier = 1
VitalityMultiplier = 1
VitalityParagonMultiplier = 1

AutoSaveQuests = false
ForceMinimapVisibility = false

; Log Output Settings
[AnsiLog]
Enabled = true
Target = Ansi
IncludeTimeStamps = true
MinimumLevel = MethodTrace
MaximumLevel = Fatal

[ConsoleLog]
Enabled = false
Target = Console
IncludeTimeStamps = true
MinimumLevel = MethodTrace
MaximumLevel = Fatal

[PacketLog]
Enabled = true
Target = file
FileName = packet.log
IncludeTimeStamps = true
MinimumLevel = Debug
MaximumLevel = PacketDump
